services:
  backend:
    image: golang:1.21
    container_name: backend
    volumes:
      - ./backend:/backend
    working_dir: /backend
    ports:
      - 3000:3000
    command: go run src/server.go
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - backend
    command: npx vite
  nginx:
    image: nginx
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
#  db:
#    image: postgres
