services:
  backend:
    image: golang:1.21
    container_name: backend
    volumes:
      - ./backend:/backend
    working_dir: /backend
    ports:
      - 3000:3000
    command: go run main.go
    environment:
      - SERVER_SECRET=${SERVER_SECRET}
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - backend
    command: npx vite
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"  # Anonymous volume to hide local node_modules
  nginx:
    image: nginx
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - db-volume:/etc/orange-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=db
volumes:
  db-volume: