services:
  backend:
    image: golang:1.21
    volumes:
      - ./backend:/backend
    working_dir: /backend
    ports:
      - 3000:3000
    command: go run src/server.go
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
    working_dir: /app
    ports:
      - 8080:8080
    depends_on:
      - backend
    command: npx vite
#  db:
#    image: postgres
